"""Unit tests for the launcher half of `providers.py`, and for the cache.

Two halves, because the claim T-00 makes is two claims. The Python half pins
what the verbs answer: which entries become a `cc_provider` call, which are
skipped, which refuse to be one, and the exact argv a launch gets. The shell
half runs ai/claude/providers.zsh against a checkout of its own and checks the
thing the file exists for — that a warm shell start reads the cache and forks
nothing, that a cold one rewrites it, and that a registry nobody can parse costs
one warning rather than the `ccd` command.

The shell cases need a zsh and the `/usr/bin/python3` the cache calls by name;
they skip without either. Nothing here reads the ambient environment: every case
runs in a tree built under `tmp_path`, so `HERDR_TEAM_ROOT` and `DOTFILES` — both
exported by the herdr pane this suite is usually run from — cannot reach the
file under test.

`run.sh` is the end-to-end suite and keeps the frozen texts that say a `team.sh`
reading this registry still spawns what it spawned before; what is pinned here
is the generation that feeds it.
"""

from __future__ import annotations

import os
import shlex
import shutil
import subprocess
from pathlib import Path
from typing import Any

import providers
import pytest

DOTFILES = Path(__file__).resolve().parents[3]
REGISTRY = DOTFILES / "ai/providers.toml"
PROVIDERS_ZSH = DOTFILES / "ai/claude/providers.zsh"

# The one line `cc-providers` prints for the shipped registry, byte for byte:
# a `cc_provider` call generated from `ai/providers.toml` has to define exactly
# what the hand-written one at the foot of providers.zsh defined before it.
DEEPSEEK_LINE = (
    "deepseek   claude-deepseek / ccd https://api.deepseek.com/anthropic  "
    "model=deepseek-flash"
)

ZSH = shutil.which("zsh")
needs_shell = pytest.mark.skipif(
    ZSH is None or not Path("/usr/bin/python3").exists(),
    reason="needs a zsh and the /usr/bin/python3 the launcher cache runs",
)


# --- registries written by hand ---------------------------------------------


def _toml(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, dict):
        return "{ %s }" % ", ".join("%s = %s" % (k, _toml(v)) for k, v in value.items())
    if isinstance(value, list):
        return "[%s]" % ", ".join(_toml(item) for item in value)
    return '"%s"' % value


def entry(name: str, **fields: Any) -> str:
    """One `[provider.<name>]` table, as the TOML text of it."""
    return "\n".join(
        ["[provider.%s]" % name]
        + ["%s = %s" % (key, _toml(value)) for key, value in fields.items()]
    )


def write_registry(tmp_path: Path, *entries: str) -> Path:
    path = tmp_path / "providers.toml"
    path.write_text("schema = 1\n\n%s\n" % "\n\n".join(entries))
    return path


def workable(**overrides: Any) -> dict[str, Any]:
    """An entry that passes lint, so a case can vary the one field it tests."""
    fields: dict[str, Any] = {
        "protocol": "anthropic",
        "url": "https://api.example.com/anthropic",
        "key": "env:EXAMPLE_API_KEY",
        "models": {"default": "example-model"},
        "launcher": {"short": "ccx"},
    }
    fields.update(overrides)
    return fields


def calls(text: str) -> list[str]:
    """The `cc_provider` lines of generated cache text, comments dropped."""
    return [line for line in text.splitlines() if line.startswith("cc_provider ")]


# --- what `zsh` emits -------------------------------------------------------


def test_the_shipped_registry_emits_one_launcher() -> None:
    # Eight entries, one launcher: the seven others are disabled, are a
    # credential another harness holds, or are the Pro login — none of which is
    # a `cc_provider` call, and every one of which would be a command that fails
    # when it ran.
    assert calls(providers.zsh()) == [
        "cc_provider deepseek url=https://api.deepseek.com/anthropic "
        "key=env:CLAUDE_CODE_DEEPSEEK_API_KEY model=deepseek-flash label=DS short=ccd"
    ]


def test_the_generated_text_says_where_it_came_from() -> None:
    # The cache is sourced by every shell start and lives in ~/.cache, so a
    # reader who opens it has to be told not to edit it, and which file to edit.
    text = providers.zsh()
    assert text.startswith("# Generated by `python3 -m providers zsh`")
    assert text.endswith("\n")
    assert not text.endswith("\n\n")


def test_the_emitted_call_is_the_argv_cc_provider_takes(tmp_path: Path) -> None:
    # Not a string comparison: the emitted line is sourced by providers.zsh, so
    # what matters is the argv `cc_provider` receives. A label with a space is
    # the case a hand-written call got right by quoting and a generator loses by
    # forgetting to.
    assert ZSH is not None
    text = providers.zsh(
        write_registry(
            tmp_path,
            entry("alpha", **workable(launcher={"short": "cca", "label": "Alpha Pro"})),
        )
    )
    cache = tmp_path / "emitted.zsh"
    cache.write_text(text)
    done = subprocess.run(
        [
            ZSH,
            "-f",
            "-c",
            'cc_provider() { print -rC1 -- "$@" }\nsource %s' % shlex.quote(str(cache)),
        ],
        capture_output=True,
        text=True,
        check=False,
    )
    assert done.returncode == 0, done.stderr
    assert done.stdout.splitlines() == [
        "alpha",
        "url=https://api.example.com/anthropic",
        "key=env:EXAMPLE_API_KEY",
        "model=example-model",
        "label=Alpha Pro",
        "short=cca",
    ]


def test_a_disabled_or_launcherless_entry_is_skipped(tmp_path: Path) -> None:
    # The shipped registry's shape written out small, once per reason to skip:
    # a disabled entry defines no launcher yet, an entry with no launcher is a
    # credential something else launches, and the two ends are there to say the
    # order is the file's and not a sorted list of whatever survived.
    without_launcher = workable()
    del without_launcher["launcher"]
    path = write_registry(
        tmp_path,
        entry("one", **workable()),
        entry("two", **workable(enabled=False)),
        entry("three", **without_launcher),
        entry("four", **workable(harnesses=["omp"])),
        entry("five", **workable()),
    )
    assert [call.split()[1] for call in calls(providers.zsh(path))] == ["one", "five"]


def test_a_provider_for_another_harness_is_not_a_launcher(tmp_path: Path) -> None:
    # `deepseek-omp`'s shape: a launcher table and a url for a harness that is
    # not claude. `cc_provider` defines claude commands, so this defines nothing.
    path = write_registry(
        tmp_path, entry("omp", **workable(harnesses=["omp"], launcher={"short": "ccx"}))
    )
    assert calls(providers.zsh(path)) == []


@pytest.mark.parametrize("missing", ["url", "key", "models"])
def test_a_launcher_that_cannot_work_raises(tmp_path: Path, missing: str) -> None:
    # A launcher is a promise that a command will exist. `url`, `key` and a
    # model are what `cc_provider` requires, so an entry missing one raises here
    # — where the warning names the file — instead of defining a command that
    # fails on every shell start, or none at all without saying why.
    fields = workable()
    del fields[missing]
    path = write_registry(tmp_path, entry("broken", **fields))
    with pytest.raises(providers.RegistryError) as raised:
        providers.zsh(path)
    assert str(path) in str(raised.value)
    assert "provider.broken cannot be a launcher" in str(raised.value)
    assert missing in str(raised.value)


@needs_shell
def test_the_generated_text_is_valid_zsh() -> None:
    # providers.zsh checks this itself before installing a cache; the check is
    # only as good as the text passing it.
    assert ZSH is not None
    done = subprocess.run(
        [ZSH, "-n"], input=providers.zsh(), text=True, capture_output=True, check=False
    )
    assert done.returncode == 0, done.stderr


# --- serves -----------------------------------------------------------------


def test_serves_defaults_to_claude_only() -> None:
    assert providers.serves({}) is True
    assert providers.serves({}, "claude") is True
    assert providers.serves({}, "omp") is False
    assert providers.serves({"harnesses": ["omp"]}, "omp") is True
    assert providers.serves({"harnesses": ["omp"]}, "claude") is False
    assert providers.serves({"harnesses": ["claude", "codex"]}, "codex") is True


def test_serves_ignores_a_harnesses_that_is_not_a_list() -> None:
    # A substring match on `"omp"` would answer yes to a string that lint is
    # about to name; the default answers the question the entries written before
    # the field existed were written to answer.
    assert providers.serves({"harnesses": "omp"}, "claude") is True
    assert providers.serves({"harnesses": "omp"}, "omp") is False


# --- launch-args ------------------------------------------------------------


def test_a_claude_launch_needs_no_words() -> None:
    # The injection is the ANTHROPIC_* environment `_cc_run` exports from this
    # same entry, so the answer is nothing to append to the command line — for a
    # keyed entry and for the Pro login alike.
    assert providers.launch_args("deepseek", "claude") == []
    assert providers.launch_args("deepseek") == []
    assert providers.launch_args("anthropic-pro", "claude") == []


def test_a_disabled_provider_has_no_launch() -> None:
    with pytest.raises(providers.RegistryError) as raised:
        providers.launch_args("kimi", "claude")
    assert "kimi is disabled" in str(raised.value)


def test_a_harness_a_provider_does_not_serve_refuses() -> None:
    with pytest.raises(providers.RegistryError) as raised:
        providers.launch_args("deepseek", "omp")
    assert "does not serve omp" in str(raised.value)


def test_a_harness_with_no_recorded_injection_refuses() -> None:
    # `deepseek-omp` does serve omp, and nothing here knows what omp is handed:
    # the plan marks that plumbing unverified, and a guessed argument is a pane
    # pointed at an endpoint nobody has tried, which fails as a hang.
    with pytest.raises(providers.RegistryError) as raised:
        providers.launch_args("deepseek-omp", "omp")
    assert "nothing here records how omp is given a provider" in str(raised.value)


# --- the verbs --------------------------------------------------------------


def test_zsh_exits_zero_and_prints_the_cache(
    capsys: pytest.CaptureFixture[str],
) -> None:
    assert providers.main(["zsh"]) == 0
    assert calls(capsys.readouterr().out) == calls(providers.zsh())


def test_zsh_refuses_arguments(capsys: pytest.CaptureFixture[str]) -> None:
    assert providers.main(["zsh", "extra"]) == 2
    assert "usage: providers zsh" in capsys.readouterr().err


def test_launch_args_prints_one_empty_line(capsys: pytest.CaptureFixture[str]) -> None:
    # A caller building a command line appends what it gets, so "nothing to
    # inject" is an empty word list and not a failure.
    assert providers.main(["launch-args", "deepseek"]) == 0
    assert capsys.readouterr().out == "\n"


def test_launch_args_reports_a_refusal_on_stderr(
    capsys: pytest.CaptureFixture[str],
) -> None:
    assert providers.main(["launch-args", "openrouter", "claude"]) == 1
    captured = capsys.readouterr()
    assert captured.out == ""
    assert captured.err.startswith("providers: ")
    assert "disabled" in captured.err


def test_the_verbs_reject_the_wrong_number_of_arguments(
    capsys: pytest.CaptureFixture[str],
) -> None:
    assert providers.main([]) == 2
    assert providers.main(["launch-args"]) == 2
    assert providers.main(["launch-args", "deepseek", "claude", "extra"]) == 2
    assert providers.main(["nonsense"]) == 2
    assert "unknown verb nonsense" in capsys.readouterr().err


# --- the cache, in a checkout of its own ------------------------------------


def isolated(tmp_path: Path) -> Path:
    """A checkout holding only what a shell start touches.

    Copies rather than symlinks, and that is the point: `providers.py` resolves
    its own path to find the registry, so a symlinked `lib/` would read the
    shipped file however the copy under test was edited — the one thing the
    cases below are about.
    """
    root = tmp_path / "dotfiles"
    lib = root / "ai/herdr/lib"
    (root / "ai/claude").mkdir(parents=True)
    lib.mkdir(parents=True)
    shutil.copy(DOTFILES / "ai/herdr/lib/providers.py", lib / "providers.py")
    shutil.copytree(DOTFILES / "ai/herdr/lib/_vendor", lib / "_vendor")
    shutil.copy(REGISTRY, root / "ai/providers.toml")
    shutil.copy(PROVIDERS_ZSH, root / "ai/claude/providers.zsh")
    return root


def cache_of(root: Path) -> Path:
    return root / "cache/dotfiles/providers.zsh"


def start(root: Path, *commands: str) -> subprocess.CompletedProcess[str]:
    """A shell start against `root`, with its cache somewhere disposable.

    `-f` so no rc file of the machine running the suite is read, and an
    environment built from scratch for the same reason: what the cache reads is
    `DOTFILES` and `XDG_CACHE_HOME`, and both point inside `root`.
    """
    assert ZSH is not None
    env = {
        "PATH": os.environ.get("PATH", "/usr/bin:/bin"),
        "HOME": str(root),
        "DOTFILES": str(root),
        "XDG_CACHE_HOME": str(root / "cache"),
        "SHELL_SESSIONS_DISABLE": "1",
    }
    script = "\n".join(
        ['source "$DOTFILES/ai/claude/providers.zsh"', *commands, "exit"]
    )
    return subprocess.run(
        [ZSH, "-f", "-c", script], capture_output=True, text=True, env=env, check=False
    )


def fingerprint(path: Path) -> tuple[int, int, bytes]:
    stat = path.stat()
    return stat.st_ino, stat.st_mtime_ns, path.read_bytes()


@needs_shell
def test_a_cold_start_writes_the_cache(tmp_path: Path) -> None:
    root = isolated(tmp_path)
    done = start(root, "cc-providers")
    assert done.stderr == ""
    assert cache_of(root).exists()
    assert done.stdout.splitlines() == [DEEPSEEK_LINE]


@needs_shell
def test_a_warm_start_reuses_the_cache(tmp_path: Path) -> None:
    # The mtime check and nothing else: a start that forked python3 or rewrote
    # the file would show up in the inode, because the refresh installs a temp
    # file with `mv` — a no-op reinstall of the same bytes is not silent.
    root = isolated(tmp_path)
    warm = start(root, "cc-providers")
    before = fingerprint(cache_of(root))
    again = start(root, "cc-providers")
    assert again.stderr == ""
    assert again.stdout == warm.stdout
    assert fingerprint(cache_of(root)) == before


@needs_shell
def test_an_edited_registry_is_regenerated(tmp_path: Path) -> None:
    root = isolated(tmp_path)
    start(root, "cc-providers")
    before = fingerprint(cache_of(root))
    registry = root / "ai/providers.toml"
    registry.write_text(
        registry.read_text()
        + "\n"
        + entry("second", **workable(launcher={"short": "ccs"}))
        + "\n"
    )
    done = start(
        root, "cc-providers", "typeset -f ccs >/dev/null && print -r -- ccs-defined"
    )
    assert done.stderr == ""
    assert fingerprint(cache_of(root)) != before
    assert done.stdout.splitlines() == [
        DEEPSEEK_LINE,
        "second     claude-second / ccs https://api.example.com/anthropic  model=example-model",
        "ccs-defined",
    ]


@needs_shell
def test_an_edited_generator_is_regenerated(tmp_path: Path) -> None:
    # The other half of the freshness test, and the one a pull exercises: the
    # generator is rewritten in place and the registry is untouched, so a cache
    # that only watched ai/providers.toml would keep emitting the old calls.
    root = isolated(tmp_path)
    start(root, "cc-providers")
    before = fingerprint(cache_of(root))
    os.utime(root / "ai/herdr/lib/providers.py", None)
    start(root, "cc-providers")
    assert fingerprint(cache_of(root)) != before


@needs_shell
def test_a_broken_registry_keeps_the_last_good_cache(tmp_path: Path) -> None:
    # The failure mode this file is written around: a registry that does not
    # parse costs one warning, not the `ccd` command. The cache is left exactly
    # as it was — not emptied, not half-written.
    root = isolated(tmp_path)
    start(root, "cc-providers")
    before = fingerprint(cache_of(root))
    registry = root / "ai/providers.toml"
    registry.write_text("[provider.deepseek\nbroken = \n")
    done = start(
        root, "cc-providers", "typeset -f ccd >/dev/null && print -r -- ccd-defined"
    )
    assert done.returncode == 0
    assert "keeping the last good cache" in done.stderr
    assert "fix ai/providers.toml" in done.stderr
    assert done.stdout.splitlines() == [DEEPSEEK_LINE, "ccd-defined"]
    assert fingerprint(cache_of(root)) == before


@needs_shell
def test_a_shell_starts_with_no_cache_and_no_registry_at_all(tmp_path: Path) -> None:
    # Worst case, and still not fatal: no cache, and nothing to build one from.
    # The shell has no provider launchers and says so once; `cc` — the Pro login,
    # which reads no registry — is defined from the file itself either way.
    root = isolated(tmp_path)
    (root / "ai/providers.toml").unlink()
    done = start(root, "typeset -f cc >/dev/null && print -r -- cc-defined")
    assert done.returncode == 0
    assert "keeping the last good cache" in done.stderr
    assert done.stdout.splitlines() == ["cc-defined"]
    assert not cache_of(root).exists()
