#!/usr/bin/env bash
# git — link ~/.gitconfig and generate the machine-local include.
set -euo pipefail

DOTFILES="${DOTFILES:-$(cd "$(dirname "$0")/.." && pwd)}"
. "${DOTFILES}/lib/common.sh"
require_macos

CURRENT_DIR="$(module_dir)"

info "Setting up git..."
link "${CURRENT_DIR}/gitconfig" "${HOME}/.gitconfig"

# git/gitconfig ends with `[include] path = ~/.config/git/gitconfig.local`.
# That file holds everything machine-specific — currently just the path to the
# Homebrew gpg, which differs between /opt/homebrew (arm64) and /usr/local.
#
# Written whole on every run, so re-running never duplicates the [gpg] block.
LOCAL_CONFIG="${HOME}/.config/git/gitconfig.local"
mkdir -p "$(dirname "${LOCAL_CONFIG}")"

GPG_PROGRAM="$(brew_prefix)/bin/gpg"
cat >"${LOCAL_CONFIG}" <<EOF
# Generated by ${DOTFILES}/git/setup.sh — do not edit by hand.
[gpg]
  program = ${GPG_PROGRAM}
EOF
ok "${LOCAL_CONFIG} (gpg.program = ${GPG_PROGRAM})"

[ -x "${GPG_PROGRAM}" ] || warn "gpg not found at ${GPG_PROGRAM}; commit signing will fail until \`brew install gpg\`."
