tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/bundle"
tap "homebrew/services"

brew "antibody"
brew "autojump"
brew "bazelisk"
brew "buildifier"
brew "git"
brew "go"
brew "mas"
brew "nodeenv"
brew "pyenv"
brew "rbenv"
brew "tldr"
brew "tmux"
brew "vim"
brew "zsh"

cask "alfred"
cask "dash"
cask "datagrip"
cask "discord"
cask "figma"
cask "flux"
cask "gitkraken"
cask "goland"
cask "google-chrome-dev"
cask "gotiengviet"
cask "intellij-idea"
cask "iterm2"
cask "miro"
cask "postman"
cask "qbittorrent"
cask "sf-symbols"
cask "skype"
cask "spotify"
cask "visual-studio-code"
cask "vlc"

cask "font-fira-code"
cask "font-fira-mono"
cask "font-fira-sans"
cask "font-fontawesome"
cask "font-inconsolata"

mas "Apple Configurator 2", id: 1037126344
mas "Keynote", id: 409183694
mas "Messenger", id: 1480068668
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Slack", id: 803453959
mas "Telegram", id: 747648890
mas "The Unarchiver", id: 425424353
mas "WhatsApp Desktop", id: 1147396723
mas "Xcode", id: 497799835
